# Generated by Django 4.1.1 on 2022-12-14 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roommember',
            old_name='room',
            new_name='room_name',
        ),
    ]
